# Site
title:              Path
bio:                'to the distant land of Valhalla . . .'
description:        "Its a personal blog, where I post about my progress in learning how to code"
reading_time:       true
words_per_minute:   150
logo:               'assets/img/placeholder_logo.jpg'
background:         'assets/img/background-eva.png'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://mnquaser.github.io/path/

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
# disqus_shortname:   taylantatli

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email: rafefanam1@gmail.com
#twitter:            username
facebook:           RafefAnam
github-url:         mnquaser
#stackoverflow:     123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:          sk-md-atahar-juhaer-rafef
#xing:              username
instagram:          mnquaser
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
